<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HeroGame.MasterServer</RootNamespace>
    <AssemblyName>herogame-master</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HeroGame.Services/HeroGame.Services.csproj" />
  </ItemGroup>
</Project>
