using System.Collections.Generic;
using System.IO;
using System.Linq;
using HeroGame.Core.Economy;
using HeroGame.Core.Simulation;
using HeroGame.Core.World;
using HeroGame.Persistence.Content;
using HeroGame.Persistence.Saves;
using NUnit.Framework;

namespace HeroGame.Tests
{
    /// <summary>The full Port Arden metro (layout_port_arden.json, generated by Tools/World/generate_metro.py).</summary>
    public class MetroLayoutTests
    {
        public const string MetroLayout = "layout_port_arden.json";

        private static ContentSet _metro;
        private static ContentSet Metro() => _metro ?? (_metro = ContentLoader.Load(TestContent.DataDirectory, MetroLayout));

        private static readonly string[] BibleDistricts =
        {
            "arden_central", "the_ledger", "harbor_row", "cotton_row", "eastwater", "southgate_flats", "channelside", "port_of_arden",
            "fairhaven", "pinecrest_hollow", "oak_terrace", "riverbend_estates", "mercer_heights", "lantana_park", "westmarch_commons",
            "coquina_key", "bitterwater_marsh", "tarrow_prairie", "kessler_field",
        };

        [Test]
        public void FullMetro_Validates_HasEveryDistrictAndLandmark_AndKeepsTheSliceIntact()
        {
            var metro = Metro();
            var report = ContentLoader.Validate(metro);
            Assert.IsFalse(report.HasErrors, report.ToString());
            CollectionAssert.AreEquivalent(BibleDistricts, metro.Layout.Districts.Select(d => d.Key).ToList());

            var names = metro.Layout.Districts.SelectMany(d => d.Places).Select(p => p.Name).ToList();
            Assert.AreEqual(names.Count, names.Distinct().Count(), "every place has its own name");
            foreach (var landmark in new[] { "Meridian Tower", "The Breakwater", "Riggers Park", "Port of Arden Container Terminal", "Coquina Key Boardwalk",
                                             "Pleasure Pier", "Founders' Square", "Port Arden City Hall", "Tarrow State University", "Halvorsen Institute",
                                             "Westmarch Commons Mall", "Calloway Chemical Works", "Arden General Hospital - East Campus", "Kessler Field Terminal" })
                CollectionAssert.Contains(names, landmark);
            Assert.IsTrue(metro.Layout.Roads.Any(r => r.Name == "Tidewater Bridge" && r.Kind == "bridge"));

            // The vertical slice is embedded verbatim, so Story Mode's places are exactly where the story expects them.
            var slice = TestContent.Load().Layout;
            foreach (var d in slice.Districts)
            {
                var copy = metro.Layout.Districts.Single(x => x.Key == d.Key);
                Assert.AreEqual(d.Places.Count, copy.Places.Count, d.Key);
                for (var i = 0; i < d.Places.Count; i++)
                {
                    Assert.AreEqual(d.Places[i].Name, copy.Places[i].Name);
                    Assert.AreEqual(d.Places[i].X, copy.Places[i].X);
                    Assert.AreEqual(d.Places[i].Z, copy.Places[i].Z);
                }
            }
            var story = ContentLoader.ValidateStory(ContentLoader.LoadStory(TestContent.DataDirectory), metro);
            Assert.IsFalse(story.HasErrors, story.ToString());

            // Every business uses a real template, with unique names across the city.
            var businesses = metro.Layout.Districts.SelectMany(d => d.Places).Where(p => p.Business != null).ToList();
            Assert.Greater(businesses.Count, 250);
            Assert.AreEqual(businesses.Count, businesses.Select(b => b.Business.Name).Distinct().Count());
        }

        [Test]
        public void FullMetro_HoldsAboutFiftyThousandResidents_OnOneConnectedRoadNetwork()
        {
            var world = WorldGenerator.Create("metro", TestContent.DefaultConfig(), Metro(), new MemoryTransactionJournal());
            Assert.That(world.Population.Count, Is.InRange(40000, 60000));
            Assert.AreEqual(19, world.Geography.Districts.Count());
            Assert.IsTrue(world.Ledger.VerifyInvariant(out _));

            // Each district has people living in it and somewhere to work, shop and get help.
            foreach (var d in world.Geography.Districts)
            {
                var places = world.Geography.Places.Where(p => p.District == d.Id).ToList();
                Assert.IsTrue(places.Any(p => p.Kind == PlaceKind.Residence || p.Kind == PlaceKind.ApartmentBuilding) || d.Key == "channelside", d.Key + " has homes");
                Assert.IsTrue(places.Any(p => p.Kind != PlaceKind.Residence && p.Kind != PlaceKind.ApartmentBuilding && p.Kind != PlaceKind.Vacant), d.Key + " has workplaces");
            }
            Assert.Greater(world.Geography.Places.Count(p => p.Kind == PlaceKind.PoliceStation), 10);
            Assert.Greater(world.Geography.Places.Count(p => p.Kind == PlaceKind.FireStation), 10);

            // One network: every road node is reachable from every other.
            var roads = world.Roads;
            var seen = new HashSet<int> { 0 };
            var queue = new Queue<int>();
            queue.Enqueue(0);
            while (queue.Count > 0)
            {
                var n = queue.Dequeue();
                foreach (var e in roads.Nodes[n].Edges)
                {
                    var other = roads.Edges[e].Other(n);
                    if (seen.Add(other)) queue.Enqueue(other);
                }
            }
            Assert.AreEqual(roads.Nodes.Count, seen.Count, "no stranded roads");

            // Same seed, same city.
            var again = WorldGenerator.Create("metro", TestContent.DefaultConfig(), Metro(), new MemoryTransactionJournal());
            Assert.AreEqual(world.Population.Count, again.Population.Count);
            Assert.AreEqual(world.Geography.PlaceCount, again.Geography.PlaceCount);
        }

        [Test]
        public void Water_ShapesTheCoast_CoquinaKeyIsAnIsland_AndNothingButDocksAndBridgesSitsInIt()
        {
            var layout = Metro().Layout;
            CollectionAssert.IsSubsetOf(new[] { "The Gulf", "Coquina Sound", "Arden Ship Canal", "Arden Ship Channel", "Arden River" }, layout.Water.Select(w => w.Name).ToList());
            var coquina = layout.Districts.Single(d => d.Key == "coquina_key");
            Assert.IsFalse(layout.IsWater(coquina.CenterX, coquina.CenterZ), "the island is land");
            // Every way off the island crosses water, so it is only reachable by bridge.
            foreach (var (dx, dz) in new[] { (-1f, 0f), (1f, 0f), (0f, 1f), (0f, -1f) })
            {
                var wet = false;
                for (var r = 0f; r < 3000f && !wet; r += 25f) wet = layout.IsWater(coquina.CenterX + dx * r, coquina.CenterZ + dz * r);
                Assert.IsTrue(wet, "water on every side of Coquina Key");
            }
            var cityHall = layout.Districts.SelectMany(d => d.Places).Single(p => p.Name == "Port Arden City Hall");
            Assert.IsFalse(layout.IsWater(cityHall.X, cityHall.Z));
            Assert.IsTrue(layout.Roads.Any(r => r.Kind == "bridge" && r.Name.Contains("Coquina")));

            // The validator refuses a building in the sea and a road that swims.
            var broken = ContentLoader.Load(TestContent.DataDirectory, MetroLayout);
            var gulf = broken.Layout.Water.Single(w => w.Name == "The Gulf");
            var shop = broken.Layout.Districts.SelectMany(d => d.Places).First(p => p.Kind == PlaceKind.Shop);
            shop.X = gulf.Points[0] + 100f;
            shop.Z = gulf.Points[1] - 100f;
            broken.Layout.Roads.Add(new RoadLayout { Name = "Swimming Street", Kind = "street", Points = { shop.X - 50f, shop.Z, shop.X + 50f, shop.Z } });
            var report = ContentLoader.Validate(broken);
            StringAssert.Contains("is in the water", report.ToString());
            StringAssert.Contains("Swimming Street", report.ToString());

            // And in play: water conducts (a power aimed at it behaves as if the ground were wet).
            var world = WorldGenerator.Create("wet", TestContent.DefaultConfig(), TestContent.Load(), new MemoryTransactionJournal());
            Assert.IsTrue(world.IsWater(new Core.Foundation.WorldPosition(0f, 0f, -830f)), "the ship canal");
            Assert.IsFalse(world.IsWater(new Core.Foundation.WorldPosition(-200f, 0f, 40f)), "Tidewater Avenue");
        }

        [Test]
        public void Saves_RememberTheirLayout_AndRefuseToOpenOnAnotherMap()
        {
            var dir = TestContent.TempDirectory("layout");
            var saves = new WorldSaveSystem(dir);
            Assert.IsNull(saves.RecordedLayoutFile(), "nothing saved yet");
            using (var journal = saves.OpenJournal())
                saves.Save(WorldGenerator.Create("layout", TestContent.DefaultConfig(), TestContent.Load(), journal), full: true);

            Assert.AreEqual(ContentLoader.DefaultLayout, saves.RecordedLayoutFile());
            using (var journal = saves.OpenJournal())
            {
                var ex = Assert.Throws<LayoutMismatchException>(() => saves.Load(Metro(), journal));
                StringAssert.Contains("vertical_slice", ex.Message);
            }
            using (var journal = saves.OpenJournal())
            {
                var reopened = saves.Load(ContentLoader.Load(TestContent.DataDirectory, saves.RecordedLayoutFile()), journal);
                Assert.IsFalse(reopened.Report.HasErrors, reopened.Report.ToString());
            }
            Assert.IsInstanceOf<IOException>(new LayoutMismatchException("x"), "hosts treat it like any other unreadable save");
        }
    }
}
