#!/usr/bin/env python3
"""Future-proofs the Unity scripts against new engine and class-library type names.

Newer Unity 6.x releases have added types whose names match ours (UnityEngine.EntityId, and
System.Diagnostics.ActivityKind from the .NET 8 class library), and every such clash stopped the editor in
Safe Mode. This check declares a stub type with the name of *every* HeroGame type in *every* non-HeroGame
namespace our scripts import (UnityEngine.*, UnityEditor, System.*, NUnit, Newtonsoft), then compiles all
Unity-side code with them (UnityCompileCheck -p:ModernBcl=true -p:ShadowTypes=true). If it compiles, no
type Unity or .NET adds later under one of our names can make a reference ambiguous.

The convention that makes this pass: `using HeroGame.*;` directives and aliases go *inside* the namespace
block, where they take precedence over the engine/BCL imports at the top of the file.

    python3 Tools/Unity/shadow_check.py
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PROJECT = os.path.join(ROOT, "Game", "Assets", "_Project")
CHECK = os.path.join(ROOT, "Headless", "UnityCompileCheck")
STUBS = os.path.join(CHECK, "obj", "ShadowTypes.g.cs")
TYPE = re.compile(r"^    (?:\[[^\n]*\]\s*)?(?:public |internal )?(?:static |sealed |abstract |partial |readonly )*"
                  r"(?:class|struct|enum|interface|delegate [\w<>\[\],. ]+?) (\w+)", re.M)
USING = re.compile(r"^using ([A-Za-z_][\w.]*);", re.M)
# "The type 'X' in '.../ShadowTypes.g.cs' conflicts with the imported type 'X' in 'UnityEngine.CoreModule, ...'":
# X already exists in the engine or class library, so real code already has to disambiguate it (the regular
# compile checks cover that) and a stub would only replace the real type.
DUPLICATE = re.compile(r"warning CS0436: The type '(\w+)' in '[^']*ShadowTypes\.g\.cs' conflicts with the imported type")


def sources():
    for root, _, files in os.walk(PROJECT):
        if "Runtime.Input" in root:  # needs the Input System package, which the compile check does not have
            continue
        for f in files:
            if f.endswith(".cs"):
                with open(os.path.join(root, f), encoding="utf-8-sig") as fh:
                    yield fh.read()


def write_stubs(names, namespaces, skip):
    os.makedirs(os.path.dirname(STUBS), exist_ok=True)
    with open(STUBS, "w", encoding="utf-8") as out:
        out.write("// Generated by Tools/Unity/shadow_check.py. Do not edit.\n")
        for ns in namespaces:
            out.write("namespace %s\n{\n" % ns)
            for n in names:
                if n not in skip:
                    out.write("    internal sealed class %s { }\n" % n)
            out.write("}\n")


def build():
    r = subprocess.run(["dotnet", "build", CHECK, "-p:ModernBcl=true", "-p:ShadowTypes=true", "-nologo", "-clp:NoSummary"],
                       capture_output=True, text=True)
    return r.returncode, r.stdout + r.stderr


def main():
    names, namespaces = set(), set()
    for text in sources():
        names.update(TYPE.findall(text))
        namespaces.update(u for u in USING.findall(text) if not u.startswith("HeroGame"))
    names, namespaces = sorted(names), sorted(namespaces)
    skip = set()
    try:
        # Pass 1 finds names that already exist in a namespace (the real type is already handled, and a stub
        # would replace it); pass 2 is the check.
        for attempt in (1, 2):
            write_stubs(names, namespaces, skip)
            code, log = build()
            found = set(DUPLICATE.findall(log)) - skip
            if attempt == 1 and found:
                skip |= found
                continue
            errors = sorted({l.strip() for l in log.splitlines() if " error " in l})
            if code != 0 or errors:
                print("\n".join(errors[:60]) or log[-4000:])
                print("\nshadow check FAILED: a HeroGame type name would clash with a future engine/BCL type. Move the "
                      "file's `using HeroGame.*;` directives inside its namespace block.")
                return 1
            print("shadow check: %d HeroGame type names x %d engine/BCL namespaces, no ambiguity (%d already exist and were "
                  "skipped)" % (len(names), len(namespaces), len(skip)))
            return 0
    finally:
        if os.path.exists(STUBS):
            os.remove(STUBS)


if __name__ == "__main__":
    sys.exit(main())
